FROM php:5.6-alpine

#---> SYSTEM <---

# install composer so it handles the php package installation
RUN echo "http://dl-3.alpinelinux.org/alpine/edge/testing" >>/etc/apk/repositories && \
    apk update && \
    apk add git composer


#---> DEPLOY <---

# create the app directory
RUN mkdir -p /var/www/app

# php packages
COPY composer.json /var/www/app/composer.json
RUN cd /var/www/app && \
    composer install

# configure phpunit
COPY phpunit.xml /var/www/app/phpunit.xml

# deploy source

# run tests
RUN cd /var/www/app && \
    phpunit
